version: ldk-v0.1a.{build}-{branch}
skip_non_tags: true
skip_branch_with_pr: true
max_jobs: 1
shallow_clone: true
build:
  verbosity: minimal
deploy:
- provider: GitHub
  description: Automated nightly build
  auth_token:
    secure: 1B78jwRfQb9JPz83VIas8ISvQPrc09h9xkfU/frT95JgH4EK+s+I7RM/1rrlum2R
  prerelease: true
  force_update: true